import type { CollectionConfig } from "payload";

import {
  revalidateCollection,
  revalidateCollectionDelete,
} from "@/payload/hooks/revalidate";
import { authenticated, adminOnly, publicRead } from "@/payload/access";

/**
 * -----------------------------------------------------------------------------
 * MEDIA — its own section, deliberately
 * -----------------------------------------------------------------------------
 * Every image on the site resolves through here rather than through a path
 * typed into whatever record happens to need it. That is what makes an asset
 * reusable: the portrait is one row referenced by the hero and by settings, not
 * two strings that can drift apart.
 *
 * ALT TEXT IS REQUIRED, AND THAT IS THE POINT
 * The field is not optional and has no default. An image whose alternative text
 * is "image" is worse than one with none, because it silences a screen reader
 * while looking like it was handled. Requiring it at the schema level means the
 * decision is made once, by the person uploading, who is the only one who knows
 * what the picture shows.
 *
 * `focalPoint` and the size set below exist so a single upload serves a hero,
 * a card and a logo without anybody re-cropping by hand. Sizes are generated by
 * sharp at upload time, so the cost is paid once rather than on every request.
 * -----------------------------------------------------------------------------
 */
export const Media: CollectionConfig = {
  slug: "media",
  admin: {
    useAsTitle: "alt",
    defaultColumns: ["filename", "alt", "kind", "updatedAt"],
    group: "Media",
  },
  access: {
    read: publicRead,
    create: authenticated,
    update: authenticated,
    delete: adminOnly,
  },
  upload: {
    mimeTypes: ["image/*"],
    focalPoint: true,
    imageSizes: [
      { name: "thumb", width: 480, withoutEnlargement: true },
      { name: "card", width: 900, withoutEnlargement: true },
      { name: "wide", width: 1920, withoutEnlargement: true },
    ],
  },
  hooks: {
    afterChange: [revalidateCollection],
    afterDelete: [revalidateCollectionDelete],
  },
  fields: [
    {
      name: "alt",
      type: "text",
      required: true,
      admin: {
        description:
          "What the image shows, for readers who cannot see it. Describe the content, not the file.",
      },
    },
    {
      name: "caption",
      type: "text",
      admin: { description: "Optional visible caption, where the layout shows one." },
    },
    {
      name: "kind",
      type: "relationship",
      relationTo: "media-kinds",
      admin: { description: "What this asset is for." },
    },
    {
      name: "credit",
      type: "text",
      admin: { description: "Attribution, where the image is not ours." },
    },
  ],
};
