/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    experience: Experience;
    education: Education;
    stats: Stat;
    technologies: Technology;
    socials: Social;
    media: Media;
    'media-kinds': MediaKind;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-kinds': MediaKindsSelect<false> | MediaKindsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    about: About;
    contact: Contact;
    'education-intro': EducationIntro;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'education-intro': EducationIntroSelect<false> | EducationIntroSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Lower numbers come first.
   */
  order: number;
  /**
   * URL segment. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Two-digit index rendered as oversized type.
   */
  index: string;
  name: string;
  category: string;
  /**
   * Employer or client, where the work was commercial.
   */
  company?: string | null;
  year: string;
  /**
   * The one-sentence thesis, used in the homepage sequence.
   */
  description: string;
  /**
   * Which generated visual represents the project.
   */
  visual:
    | 'system'
    | 'modules'
    | 'relations'
    | 'pipeline'
    | 'grid'
    | 'orbit'
    | 'scan'
    | 'strata'
    | 'flow'
    | 'edge'
    | 'topology';
  /**
   * Hex. The project's mark colour in the homepage sequence.
   */
  accent: string;
  /**
   * Short stack pills on the homepage card.
   */
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Without one the project uses the portfolio palette.
   */
  palette?: {
    enabled?: boolean | null;
    /**
     * Deep tone for full-bleed bands. Near-black.
     */
    accent?: string | null;
    accentDeep?: string | null;
    muted?: string | null;
    surface?: string | null;
    surfaceAlt?: string | null;
    surfaceSoft?: string | null;
    /**
     * Mid-tone. The only palette value that carries hue at small sizes.
     */
    warm?: string | null;
    cream?: string | null;
  };
  /**
   * Present only on projects with a published case study. A project without one still appears in the homepage sequence.
   */
  caseStudy?: {
    /**
     * Unticked: no /work page is generated.
     */
    hasCaseStudy?: boolean | null;
    statement?: string | null;
    seoDescription?: string | null;
    /**
     * Terms shown opposite the index.
     */
    heroNote?: string | null;
    /**
     * Splits the title so one half takes the project accent.
     */
    wordmark?: {
      lead?: string | null;
      tail?: string | null;
      accent?: ('lead' | 'tail') | null;
    };
    /**
     * Hero metadata column.
     */
    meta?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Hard facts set under the hero lede.
     */
    highlights?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Shown on the hero axis.
     */
    disciplines?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Which disciplines this project genuinely touches. Empty lights all of them.
     */
    covers?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Hero stack pills.
     */
    technologies?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    technicalSummary?: string | null;
    /**
     * Human label — Public or Private.
     */
    repository?: string | null;
    /**
     * PUBLIC repositories only. A private one must not carry a link: GitHub answers it with a 404 for anyone without access.
     */
    repositoryUrl?: string | null;
    publicArtifacts?: string | null;
    evidence?: {
      supported?: string | null;
      notOverstated?: string | null;
    };
    /**
     * The numbered body of the case study, in order.
     */
    sections?:
      | {
          /**
           * Anchor id.
           */
          sectionId: string;
          number: string;
          title: string;
          tone?: ('paper' | 'surface' | 'soft' | 'alt' | 'sage' | 'deep') | null;
          figure?:
            | (
                | 'relation'
                | 'architecture'
                | 'stack'
                | 'infrastructure'
                | 'domain'
                | 'techniques'
                | 'responsibility'
                | 'disclosure'
                | 'status'
                | 'phases'
                | 'research-architecture'
                | 'metrics'
                | 'capabilities'
                | 'planned'
                | 'process-topology'
                | 'aggregation'
                | 'limits'
                | 'growth'
                | 'proof'
                | 'tradeoff'
                | 'gap'
              )
            | null;
          /**
           * One entry per paragraph.
           */
          body: {
            value: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[]
      | null;
    /**
     * Editorial keywords for the interaction layer.
     */
    techniques?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Everyone who worked on it. Not optional on a shared project.
     */
    contributors?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Named people and roles, where a flat list is not enough.
     */
    credits?:
      | {
          name: string;
          role?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Current state. Unticked rows render as outstanding.
     */
    status?:
      | {
          label: string;
          value: string;
          /**
           * Ticked means delivered. Unticked renders as outstanding.
           */
          available?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * A direction that is planned rather than delivered.
     */
    planned?:
      | {
          label: string;
          value: string;
          /**
           * Ticked means delivered. Unticked renders as outstanding.
           */
          available?: boolean | null;
          id?: string | null;
        }[]
      | null;
    responsibility?: {
      stages?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      caveat?: string | null;
    };
    disclosure?: {
      canShow?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      withheld?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Grouped stack notes shown under the body.
     */
    technicalNotes?:
      | {
          title: string;
          items: {
            value: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[]
      | null;
    /**
     * The request path. Heads are parallel entry points.
     */
    architecture?: {
      heads?:
        | {
            /**
             * Stable key for this layer, unique within the diagram.
             */
            layerId: string;
            label: string;
            note?: string | null;
            id?: string | null;
          }[]
        | null;
      stack?:
        | {
            /**
             * Stable key for this layer, unique within the diagram.
             */
            layerId: string;
            label: string;
            note?: string | null;
            id?: string | null;
          }[]
        | null;
      /**
       * Services beside the path rather than in it.
       */
      aside?:
        | {
            /**
             * Stable key for this layer, unique within the diagram.
             */
            layerId: string;
            label: string;
            note?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * A second, independent flow — deployment or teardown.
     */
    infrastructure?: {
      stack?:
        | {
            /**
             * Stable key for this layer, unique within the diagram.
             */
            layerId: string;
            label: string;
            note?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Entity graph. Coordinates are in the figure's own 900×560 space.
     */
    domain?: {
      nodes?:
        | {
            nodeId: string;
            label: string;
            /**
             * Scroll step at which it appears.
             */
            stage: number;
            x: number;
            y: number;
            id?: string | null;
          }[]
        | null;
      edges?:
        | {
            from: string;
            to: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Ordered stages of how it grew.
     */
    growth?:
      | {
          number: string;
          label: string;
          note: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Both columns optional — a section may be carried by the words alone.
     */
    tradeoff?: {
      left?: {
        title?: string | null;
        items?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
      };
      right?: {
        title?: string | null;
        items?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
      };
      /**
       * Editorial words that carry the section visually.
       */
      words?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Phases of work. `complete` is the point of this field: a list that renders planned work identically to delivered work reads as a finished project.
     */
    phases?:
      | {
          number: string;
          label: string;
          complete?: boolean | null;
          items?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    packages?:
      | {
          name: string;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    dataFlows?:
      | {
          label: string;
          carries: string;
          topic: string;
          to: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Measures the work is designed to capture — targets, not results.
     */
    metrics?:
      | {
          title: string;
          items: {
            value: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[]
      | null;
    /**
     * Tooling that exists, described by what it can produce.
     */
    tooling?:
      | {
          title: string;
          items: {
            value: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[]
      | null;
    /**
     * What the system does for the people using it, grouped.
     */
    capabilities?: {
      groups?:
        | {
            title: string;
            items: {
              value: string;
              id?: string | null;
            }[];
            id?: string | null;
          }[]
        | null;
      note?: string | null;
    };
    /**
     * A run of processes and the primitives between them.
     */
    topology?: {
      steps?:
        | {
            stepId: string;
            label: string;
            /**
             * Process, IPC, Threads, Memory, Output.
             */
            kind: string;
            id?: string | null;
          }[]
        | null;
      support?:
        | {
            label: string;
            note?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Low-level primitives, set large.
     */
    primitives?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * A grouping transformation, named at label level with no invented values.
     */
    aggregation?: {
      source?: string | null;
      groupBy?: string | null;
      measures?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      output?: string | null;
      note?: {
        title?: string | null;
        body?: string | null;
        formula?: string | null;
      };
    };
    /**
     * What is verified and what is not.
     */
    limits?: {
      verified?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      notVerified?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Steps that would raise confidence — none of them taken yet.
     */
    nextProof?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * A gap stated plainly rather than designed around.
     */
    gap?: {
      label?: string | null;
      subject?: string | null;
      status?: string | null;
      next?: string | null;
    };
    /**
     * Concrete support, plus the chain a single test or path actually walks.
     */
    proof?: {
      points?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Stage names only — never values, thresholds or results.
       */
      chain?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      note?: string | null;
    };
    /**
     * Concept level only — no permission matrices or route structures.
     */
    accessModel?: {
      title?: string | null;
      items?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      note?: string | null;
    };
    /**
     * Approved screenshots, resolved from the media library. The page renders no media section at all while this is empty.
     */
    media?:
      | {
          image: number | Media;
          /**
           * Overrides the asset's own caption.
           */
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for readers who cannot see it. Describe the content, not the file.
   */
  alt: string;
  /**
   * Optional visible caption, where the layout shows one.
   */
  caption?: string | null;
  /**
   * What this asset is for.
   */
  kind?: (number | null) | MediaKind;
  /**
   * Attribution, where the image is not ours.
   */
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-kinds".
 */
export interface MediaKind {
  id: number;
  label: string;
  /**
   * Stable identifier, e.g. portrait, logo, screenshot.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  /**
   * Lower numbers come first.
   */
  order: number;
  role: string;
  company: string;
  /**
   * The oversized figure on the row, e.g. 2026.
   */
  year: string;
  /**
   * Human-readable span, e.g. Jun 2026 — Present.
   */
  period: string;
  /**
   * Full-time · Part-time · Internship. Required — the row renders it beside the company.
   */
  type: string;
  location?: string | null;
  summary?: string | null;
  /**
   * Company mark. Resolved from the media library.
   */
  logo?: (number | null) | Media;
  skills?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  /**
   * Lower numbers come first.
   */
  order: number;
  /**
   * Two-digit index, e.g. 01.
   */
  number: string;
  /**
   * Small qualifier beside the index.
   */
  tag: string;
  qualification: string;
  institution?: string | null;
  /**
   * Abbreviation, e.g. FAST-NUCES.
   */
  institutionShort?: string | null;
  description: string;
  status?: string | null;
  progress?: string | null;
  /**
   * Completed only. There is deliberately no total.
   */
  semestersCompleted?: number | null;
  /**
   * Oversized treatment — only where the qualification itself is set large.
   */
  display?: {
    lead?: string | null;
    outline?: string | null;
    solid?: string | null;
  };
  /**
   * Individual grades, revealed in order.
   */
  grades?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Aggregate, where naming every grade would be noise.
   */
  gradeTally?: {
    aStars?: number | null;
    aGrades?: number | null;
  };
  achievement?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * Lower numbers come first.
   */
  order: number;
  value: string;
  label: string;
  caption: string;
  /**
   * Where this figure can be verified. Internal note — never rendered.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  /**
   * Lower numbers come first.
   */
  order: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: number;
  /**
   * Lower numbers come first.
   */
  order: number;
  label: string;
  /**
   * Full URL, or a mailto: address. An http(s) link opens in a new tab automatically.
   */
  href: string;
  icon: 'github' | 'linkedin' | 'mail';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'socials';
        value: number | Social;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-kinds';
        value: number | MediaKind;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  order?: T;
  slug?: T;
  index?: T;
  name?: T;
  category?: T;
  company?: T;
  year?: T;
  description?: T;
  visual?: T;
  accent?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  palette?:
    | T
    | {
        enabled?: T;
        accent?: T;
        accentDeep?: T;
        muted?: T;
        surface?: T;
        surfaceAlt?: T;
        surfaceSoft?: T;
        warm?: T;
        cream?: T;
      };
  caseStudy?:
    | T
    | {
        hasCaseStudy?: T;
        statement?: T;
        seoDescription?: T;
        heroNote?: T;
        wordmark?:
          | T
          | {
              lead?: T;
              tail?: T;
              accent?: T;
            };
        meta?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        highlights?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        disciplines?:
          | T
          | {
              value?: T;
              id?: T;
            };
        covers?:
          | T
          | {
              value?: T;
              id?: T;
            };
        technologies?:
          | T
          | {
              value?: T;
              id?: T;
            };
        technicalSummary?: T;
        repository?: T;
        repositoryUrl?: T;
        publicArtifacts?: T;
        evidence?:
          | T
          | {
              supported?: T;
              notOverstated?: T;
            };
        sections?:
          | T
          | {
              sectionId?: T;
              number?: T;
              title?: T;
              tone?: T;
              figure?: T;
              body?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        techniques?:
          | T
          | {
              value?: T;
              id?: T;
            };
        contributors?:
          | T
          | {
              value?: T;
              id?: T;
            };
        credits?:
          | T
          | {
              name?: T;
              role?: T;
              id?: T;
            };
        status?:
          | T
          | {
              label?: T;
              value?: T;
              available?: T;
              id?: T;
            };
        planned?:
          | T
          | {
              label?: T;
              value?: T;
              available?: T;
              id?: T;
            };
        responsibility?:
          | T
          | {
              stages?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              caveat?: T;
            };
        disclosure?:
          | T
          | {
              canShow?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              withheld?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
        technicalNotes?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        architecture?:
          | T
          | {
              heads?:
                | T
                | {
                    layerId?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              stack?:
                | T
                | {
                    layerId?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              aside?:
                | T
                | {
                    layerId?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
            };
        infrastructure?:
          | T
          | {
              stack?:
                | T
                | {
                    layerId?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
            };
        domain?:
          | T
          | {
              nodes?:
                | T
                | {
                    nodeId?: T;
                    label?: T;
                    stage?: T;
                    x?: T;
                    y?: T;
                    id?: T;
                  };
              edges?:
                | T
                | {
                    from?: T;
                    to?: T;
                    id?: T;
                  };
            };
        growth?:
          | T
          | {
              number?: T;
              label?: T;
              note?: T;
              id?: T;
            };
        tradeoff?:
          | T
          | {
              left?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                  };
              right?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                  };
              words?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
        phases?:
          | T
          | {
              number?: T;
              label?: T;
              complete?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        packages?:
          | T
          | {
              name?: T;
              note?: T;
              id?: T;
            };
        dataFlows?:
          | T
          | {
              label?: T;
              carries?: T;
              topic?: T;
              to?: T;
              id?: T;
            };
        metrics?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        tooling?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        capabilities?:
          | T
          | {
              groups?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              note?: T;
            };
        topology?:
          | T
          | {
              steps?:
                | T
                | {
                    stepId?: T;
                    label?: T;
                    kind?: T;
                    id?: T;
                  };
              support?:
                | T
                | {
                    label?: T;
                    note?: T;
                    id?: T;
                  };
            };
        primitives?:
          | T
          | {
              value?: T;
              id?: T;
            };
        aggregation?:
          | T
          | {
              source?: T;
              groupBy?: T;
              measures?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              output?: T;
              note?:
                | T
                | {
                    title?: T;
                    body?: T;
                    formula?: T;
                  };
            };
        limits?:
          | T
          | {
              verified?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              notVerified?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
        nextProof?:
          | T
          | {
              value?: T;
              id?: T;
            };
        gap?:
          | T
          | {
              label?: T;
              subject?: T;
              status?: T;
              next?: T;
            };
        proof?:
          | T
          | {
              points?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              chain?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              note?: T;
            };
        accessModel?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              note?: T;
            };
        media?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  order?: T;
  role?: T;
  company?: T;
  year?: T;
  period?: T;
  type?: T;
  location?: T;
  summary?: T;
  logo?: T;
  skills?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  order?: T;
  number?: T;
  tag?: T;
  qualification?: T;
  institution?: T;
  institutionShort?: T;
  description?: T;
  status?: T;
  progress?: T;
  semestersCompleted?: T;
  display?:
    | T
    | {
        lead?: T;
        outline?: T;
        solid?: T;
      };
  grades?:
    | T
    | {
        value?: T;
        id?: T;
      };
  gradeTally?:
    | T
    | {
        aStars?: T;
        aGrades?: T;
      };
  achievement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  order?: T;
  value?: T;
  label?: T;
  caption?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  order?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  order?: T;
  label?: T;
  href?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  kind?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-kinds_select".
 */
export interface MediaKindsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  person: {
    firstName: string;
    lastName: string;
    /**
     * Long form, e.g. AI ENGINEER · SOFTWARE DEVELOPER.
     */
    title: string;
    titleShort: string;
    intro: string;
    availability: string;
    location?: string | null;
  };
  portrait?: {
    /**
     * Transparent cutout — typography sits behind it.
     */
    cutout?: (number | null) | Media;
    original?: (number | null) | Media;
  };
  site: {
    description: string;
    builtBy?: string | null;
    /**
     * Production origin, no trailing path. Leave empty until the real deployed domain is known — a wrong absolute URL is worse than none.
     */
    url?: string | null;
  };
  /**
   * The eyebrow that opens each homepage section.
   */
  sectionLabels: {
    about: string;
    stats: string;
    work: string;
    experience: string;
    education: string;
    technologies: string;
    contact: string;
  };
  /**
   * The words that travel horizontally in the statement scene, in order.
   */
  horizontalWords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary navigation, in order.
   */
  navigation?:
    | {
        label: string;
        /**
         * Anchor, e.g. #work.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Rendered one line at a time as the section scrolls.
   */
  statement?:
    | {
        text: string;
        accent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Written from confirmed facts only — no years-of-experience figure, no project count, no claim about anything running in production.
   */
  paragraph: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  email: string;
  /**
   * One entry per display line.
   */
  headline: {
    value: string;
    id?: string | null;
  }[];
  subline: string;
  sublineAccent: string;
  cta: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education-intro".
 */
export interface EducationIntro {
  id: number;
  /**
   * Split so each line arrives on its own.
   */
  statement: {
    value: string;
    id?: string | null;
  }[];
  lede: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  person?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        title?: T;
        titleShort?: T;
        intro?: T;
        availability?: T;
        location?: T;
      };
  portrait?:
    | T
    | {
        cutout?: T;
        original?: T;
      };
  site?:
    | T
    | {
        description?: T;
        builtBy?: T;
        url?: T;
      };
  sectionLabels?:
    | T
    | {
        about?: T;
        stats?: T;
        work?: T;
        experience?: T;
        education?: T;
        technologies?: T;
        contact?: T;
      };
  horizontalWords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  statement?:
    | T
    | {
        text?: T;
        accent?: T;
        id?: T;
      };
  paragraph?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  email?: T;
  headline?:
    | T
    | {
        value?: T;
        id?: T;
      };
  subline?: T;
  sublineAccent?: T;
  cta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education-intro_select".
 */
export interface EducationIntroSelect<T extends boolean = true> {
  statement?:
    | T
    | {
        value?: T;
        id?: T;
      };
  lede?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}